Update Build_oneplus_sm8750.yml

diff --git a/.github/workflows/Build_oneplus_sm8750.yml b/.github/workflows/Build_oneplus_sm8750.yml
--- a/.github/workflows/Build_oneplus_sm8750.yml
+++ b/.github/workflows/Build_oneplus_sm8750.yml
@@ -196,7 +196,7 @@ jobs:
       - name: 📥 Initialize repo and sync (初始化repo并同步内核源码)
         run: |
          mkdir kernel_workspace && cd kernel_workspace
-         repo init -u https://github.com/showdo/kernel_manifest.git -b refs/heads/oneplus/sm8750 -m ${REPO_MANIFEST}.xml --depth=1
+         repo init -u https://github.com/Autlin/kernel_manifest.git -b refs/heads/oneplus/sm8750 -m ${REPO_MANIFEST}.xml --depth=1
          repo --trace sync -c -j$(nproc --all) --no-tags
          rm kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports!"
          rm kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports!"
@@ -208,18 +208,19 @@ jobs:
             
             curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/susfs-main/kernel/setup.sh" -o setup.sh && bash setup.sh susfs-main
             
-            cd KernelSU
-            KSU_VERSION=$(expr $(/usr/bin/git rev-list --count main) "+" 10700)
-            echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
-            cp "${GITHUB_WORKSPACE}/.github/workflows/setup.bin" ./
-            chmod +x setup.bin
-            
-            if [ ! -f "kernel/Makefile" ]; then
-              echo "::error ::kernel/Makefile not found"
-              ls -la
-              exit 1
-            fi
-            ./setup.bin
+#            cd KernelSU
+#            KSU_VERSION=$(expr $(/usr/bin/git rev-list --count main) "+" 10700)
+#            echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
+#            cp "${GITHUB_WORKSPACE}/.github/workflows/setup.bin" ./
+#            chmod +x setup.bin
+#            
+#            if [ ! -f "kernel/Makefile" ]; then
+#              echo "::error ::kernel/Makefile not found"
+#              ls -la
+#              exit 1
+#            fi
+#            ./setup.bin
+
       - name: 🔧 Set up SUSFS (配置 SUSFS)
         run: |
            cd kernel_workspace
@@ -265,7 +266,7 @@ jobs:
           PATCH_FILE="${{ runner.temp }}/hmbird_patch.c"
           if [ ! -f "$PATCH_FILE" ]; then
             echo "下载HMBird补丁..."
-            curl -sSLo "$PATCH_FILE" https://raw.githubusercontent.com/showdo/build_oneplus_sm8750/main/hmbird_patch.c
+            curl -sSLo "$PATCH_FILE" https://raw.githubusercontent.com/Autlin/build_oneplus_sm8750/main/hmbird_patch.c
           fi
           
           cd kernel_workspace/kernel_platform/common/drivers
@@ -435,7 +436,7 @@ jobs:
          
       - name: 📦 Make AnyKernel3 (KPM)
         run: |
-         git clone https://github.com/showdo/AnyKernel3.git --depth=1      
+         git clone https://github.com/Kernel-SU/AnyKernel3.git --depth=1     
          rm -rf ./AnyKernel3/.git
          rm -rf ./AnyKernel3/push.sh
          cp kernel_workspace/kernel_platform/common/out/arch/arm64/boot/Image ./AnyKernel3/
